//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Bingo.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCarton", Namespace="http://schemas.datacontract.org/2004/07/WCF_Bingo.Clases")]
    [System.SerializableAttribute()]
    public partial class clsCarton : UI_Bingo.ServiceReference1.clsCartonModelo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadNumerosAJugarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroAReducirParaGanarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadNumerosAJugar {
            get {
                return this.CantidadNumerosAJugarField;
            }
            set {
                if ((this.CantidadNumerosAJugarField.Equals(value) != true)) {
                    this.CantidadNumerosAJugarField = value;
                    this.RaisePropertyChanged("CantidadNumerosAJugar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroAReducirParaGanar {
            get {
                return this.NumeroAReducirParaGanarField;
            }
            set {
                if ((this.NumeroAReducirParaGanarField.Equals(value) != true)) {
                    this.NumeroAReducirParaGanarField = value;
                    this.RaisePropertyChanged("NumeroAReducirParaGanar");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCartonModelo", Namespace="http://schemas.datacontract.org/2004/07/WCF_Bingo.Clases")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UI_Bingo.ServiceReference1.clsCarton))]
    public partial class clsCartonModelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UI_Bingo.ServiceReference1.clsCelda[][] ColumnasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UI_Bingo.ServiceReference1.clsCelda[][] Columnas {
            get {
                return this.ColumnasField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnasField, value) != true)) {
                    this.ColumnasField = value;
                    this.RaisePropertyChanged("Columnas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCelda", Namespace="http://schemas.datacontract.org/2004/07/WCF_Bingo.Clases")]
    [System.SerializableAttribute()]
    public partial class clsCelda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AJugarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AJugar {
            get {
                return this.AJugarField;
            }
            set {
                if ((this.AJugarField.Equals(value) != true)) {
                    this.AJugarField = value;
                    this.RaisePropertyChanged("AJugar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsJugador", Namespace="http://schemas.datacontract.org/2004/07/WCF_Bingo.Clases")]
    [System.SerializableAttribute()]
    public partial class clsJugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCantidadCartonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UI_Bingo.ServiceReference1.clsCarton[] listaCartonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCantidadCartones {
            get {
                return this.iCantidadCartonesField;
            }
            set {
                if ((this.iCantidadCartonesField.Equals(value) != true)) {
                    this.iCantidadCartonesField = value;
                    this.RaisePropertyChanged("iCantidadCartones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UI_Bingo.ServiceReference1.clsCarton[] listaCartones {
            get {
                return this.listaCartonesField;
            }
            set {
                if ((object.ReferenceEquals(this.listaCartonesField, value) != true)) {
                    this.listaCartonesField = value;
                    this.RaisePropertyChanged("listaCartones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreUsuario {
            get {
                return this.sNombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.sNombreUsuarioField, value) != true)) {
                    this.sNombreUsuarioField = value;
                    this.RaisePropertyChanged("sNombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getJugador", ReplyAction="http://tempuri.org/IService1/getJugadorResponse")]
        UI_Bingo.ServiceReference1.clsJugador getJugador(string p_sNombreUsuario, int p_iCantidadCartones, UI_Bingo.ServiceReference1.clsCarton[] p_ListaCartones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getJugador", ReplyAction="http://tempuri.org/IService1/getJugadorResponse")]
        System.Threading.Tasks.Task<UI_Bingo.ServiceReference1.clsJugador> getJugadorAsync(string p_sNombreUsuario, int p_iCantidadCartones, UI_Bingo.ServiceReference1.clsCarton[] p_ListaCartones);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UI_Bingo.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UI_Bingo.ServiceReference1.IService1>, UI_Bingo.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UI_Bingo.ServiceReference1.clsJugador getJugador(string p_sNombreUsuario, int p_iCantidadCartones, UI_Bingo.ServiceReference1.clsCarton[] p_ListaCartones) {
            return base.Channel.getJugador(p_sNombreUsuario, p_iCantidadCartones, p_ListaCartones);
        }
        
        public System.Threading.Tasks.Task<UI_Bingo.ServiceReference1.clsJugador> getJugadorAsync(string p_sNombreUsuario, int p_iCantidadCartones, UI_Bingo.ServiceReference1.clsCarton[] p_ListaCartones) {
            return base.Channel.getJugadorAsync(p_sNombreUsuario, p_iCantidadCartones, p_ListaCartones);
        }
    }
}
